[2018-08-03 20:29:30,676] {/home/pavin/.local/lib/python3.5/site-packages/flask/app.py:1761} ERROR - Exception on /recognize [POST]
Traceback (most recent call last):
  File "/home/pavin/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pavin/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pavin/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pavin/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pavin/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pavin/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 54, in recognize
    cycler = Cycler.Cycler(crop,bBoxes)
TypeError: __init__() missing 1 required positional argument: 'charClass'
